apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  namespace: fastapi-namespace  # Change this if needed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: docker.io/adarsh247/ms-test:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
